# Generated by Django 3.0.8 on 2020-07-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(max_length=300)),
                ('field_2', models.CharField(max_length=300)),
                ('field_3', models.DateTimeField()),
            ],
        ),
    ]
