# Generated by Django 3.0.8 on 2020-07-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_testmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='field_3',
        ),
    ]
