# Generated by Django 3.0.8 on 2020-07-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_testmodel_field_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='textbox_text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
